### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by Shahzaib1999** [zeeshan87/Front-End-Web-UI-Frameworks-and-Tools-Bootstrap-4#1]
Assignment 2 is in completed

**Comment by zeeshan87** [comment]
Need more specific information..

**Comment by Shahzaib1999** [comment]
In the reservation form the radio button is missing.

**Comment by zeeshan87** [comment]
I just tested it on jsfiddler, it's working. My assumption is that you're using a newer version of bootstrap. The repository uses beta 2 and I have also tested it on alpha 6. Try reverting to that.

I now have to close it because the repository is provided as is, and as mentioned in the readme: this repository is only for the information/audit purposes, don't use it to copy the assignments if you're also taking the course.
